### PR TITLE
 rank.java

### PR DESCRIPTION
**Pull request by IndrashisChatterjee**
returns rank of each element in an array

### CODE REVIEW

**Comment by IndrashisChatterjee** [comment]
kindly merge the contribution

**Comment by IndrashisChatterjee** [comment]
Please add hacktoberfest-accepted in the labels..otherwise it won't reflect

**Comment by Dhaneha-Shiyamkumar** [comment]
Okay sure

**Comment by Dhaneha-Shiyamkumar** [comment]
Can you req me again?

**Comment by IndrashisChatterjee** [comment]
U mean pull request right ?

**Comment by Dhaneha-Shiyamkumar** [comment]
Yep so that i can add the label

**Pull request merged**
